# Generated by Django 4.0 on 2022-01-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_numberofquotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberOfQuotes',
        ),
    ]
