# Generated by Django 4.0 on 2022-01-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=265, unique=True)),
        ),
    ]
