# Generated by Django 4.0 on 2022-01-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_userinfo_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
